# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-08 00:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=50)),
                ('trunk', models.CharField(max_length=50)),
                ('features', models.CharField(max_length=200)),
                ('desc', models.CharField(max_length=30)),
            ],
        ),
    ]
