# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-08 00:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobiles', '0003_auto_20170608_0028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mobile',
            old_name='desc',
            new_name='name',
        ),
    ]
