# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-08 00:49
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobiles', '0004_auto_20170608_0032'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobile',
            name='price',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=20),
        ),
    ]
