# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-08 02:26
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobiles', '0005_mobile_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=20)),
                ('products', models.ManyToManyField(to='mobiles.Mobile')),
            ],
        ),
    ]
